import { useEffect, useRef, useState } from "react";
import { t, useLanguage } from "../language";
import { ArrowUpRight, Heart, Sparkles, Users, MapPin, CalendarDays, Check, X, ChevronDown, MessageCircle, Globe, SlidersHorizontal } from "lucide-react";

const celebrations = [
  { title: "Bodas", subtitle: "El comienzo de una historia juntos.", description: "Un espacio para compartir la ilusión de ese día y reunir los detalles que quieres contar a tus invitados.", image: "/demo-wedding-v2.jpg", Icon: Heart, message: "una página para mi boda", englishMessage: "a wedding website", theme: "wedding", kicker: "NOS CASAMOS", name: "Valeria & Mateo", date: "18 · 09 · 2027", place: "Jardín Magnolia", time: "17:00", greeting: "Una nueva historia juntos.", englishGreeting: "A new story together." },
  { title: "Cumpleaños y celebraciones", subtitle: "Hay momentos que merecen algo especial.", description: "Una invitación con tu personalidad, para que la emoción de celebrar empiece desde el primer vistazo.", image: "/demo-birthday-v2.jpg", Icon: Sparkles, message: "una página para mi celebración", englishMessage: "a celebration website", theme: "birthday", kicker: "ESTÁS INVITADO", name: "Sofía · 25", date: "24 · 07 · 2027", place: "Terraza Aurora", time: "19:00", greeting: "Hoy toca celebrar.", englishGreeting: "It's time to celebrate." },
  { title: "Eventos y encuentros", subtitle: "Buenas ideas. Personas que conectan.", description: "Dale a tu encuentro un lugar propio en la web para presentar su esencia y compartir la información del evento.", image: "/demo-creative-v2.jpg", Icon: Users, message: "una página para mi evento", englishMessage: "an event website", theme: "gathering", kicker: "ENCUENTRO CREATIVO", name: "Conexión / 27", date: "12 · 06 · 2027", place: "Espacio Nodo", time: "10:00", greeting: "Ideas que nos conectan.", englishGreeting: "Ideas that connect us." },
];

export function Events() {
  const language = useLanguage();
  const english = language === "en";
  const [active, setActive] = useState(0);
  const [expanded, setExpanded] = useState(false);
  const [revealed, setRevealed] = useState(false);
  const selectorRef = useRef<HTMLDivElement>(null);
  useEffect(() => {
    const element = selectorRef.current;
    if (!element) return;
    const observer = new IntersectionObserver(entries => {
      if (entries.some(entry => entry.isIntersecting)) {
        setRevealed(true);
        observer.disconnect();
      }
    }, { threshold: 0.15 });
    observer.observe(element);
    return () => observer.disconnect();
  }, []);
  const [detail, setDetail] = useState<"location" | "agenda" | "rsvp" | null>(null);
  const event = celebrations[active];
  const Icon = event.Icon;
  const experience = active === 1 ? {
    guestTitle: english ? "The celebration starts before the party." : "La celebración empieza antes de la fiesta.",
    guestCopy: english ? "Share the birthday person's story, the party theme and everything guests need to join the celebration." : "Comparte la historia del festejado, la temática y todo lo que tus invitados necesitan para sumarse a la celebración.",
    features: english ? [["Photos & memories", "A gallery with the birthday person's personality."], ["Theme & dress code", "Colors, costumes or the style of the party."], ["Date & party schedule", "Arrival, activities and the big moments."], ["Location & useful details", "Directions, gifts and recommendations."]] : [["Fotos y recuerdos", "Una galería con la personalidad del festejado."], ["Temática y vestimenta", "Colores, disfraces o el estilo de la fiesta."], ["Fecha y programa", "Llegada, actividades y momentos especiales."], ["Ubicación y detalles", "Cómo llegar, regalos y recomendaciones."]],
    owner: english ? "FOR THE HOST" : "PARA QUIEN ORGANIZA",
    ownerTitle: english ? "More celebrating. Clearer planning." : "Más emoción. Mejor organización.",
    ownerCopy: english ? "We can include a private dashboard with guests, RSVPs and companions so you can plan your celebration." : "Podemos incluir un panel privado con invitados, confirmaciones y acompañantes para ayudarte a preparar la celebración.",
    list: english ? "Party guests" : "Invitados a la fiesta", total: 60, confirmed: 42, pending: 18, percent: 70,
    progress: english ? "The party is coming together" : "La fiesta ya toma forma",
  } : {
    guestTitle: english ? "Connect before you arrive." : "Conecta desde antes de llegar.",
    guestCopy: english ? "A home for your gathering: discover its purpose, meet the speakers and explore the program from one link." : "Un espacio para tu encuentro: conoce su propósito, descubre a los ponentes y consulta el programa desde un solo enlace.",
    features: english ? [["Speakers & participants", "Profiles, topics and people to discover."], ["Program & sessions", "Times, activities and rooms in one place."], ["Venue & directions", "Location, access and recommendations."], ["Resources & updates", "Useful links and news about the gathering."]] : [["Ponentes y participantes", "Perfiles, temas y personas por descubrir."], ["Programa y sesiones", "Horarios, actividades y salas en un lugar."], ["Sede y cómo llegar", "Ubicación, accesos y recomendaciones."], ["Recursos y novedades", "Enlaces útiles y noticias del encuentro."]],
    owner: english ? "FOR YOUR TEAM" : "PARA TU EQUIPO",
    ownerTitle: english ? "Your gathering, with a clear overview." : "Tu encuentro, con una visión clara.",
    ownerCopy: english ? "We can include a private dashboard to consult registrations, available capacity and attendance. Features depend on your event's scope." : "Podemos incluir un dashboard privado para consultar registros, cupos disponibles y asistencia. Las funciones se definen según el alcance de tu evento.",
    list: english ? "Event registrations" : "Registros al encuentro", total: 150, confirmed: 108, pending: 42, percent: 72,
    progress: english ? "Your community is growing" : "Tu comunidad crece",
  };
  const labels = english ? ["Weddings", "Celebrations", "Gatherings"] : ["Bodas", "Celebraciones", "Encuentros"];
  const contact = `https://wa.me/528111197607?text=${encodeURIComponent(english ? `Hi! I am interested in ${event.englishMessage} from Nordra Studio. I would like to discuss the details.` : `¡Hola! Me interesa ${event.message} de Nordra Studio. Me gustaría platicar sobre los detalles.`)}`;
  return (
    <section id="eventos" className="section celebrations-section" aria-labelledby="celebrations-title">
      <div className="site-shell">
        <div className="celebrations-heading"><p className="eyebrow">{t("EVENTOS Y CELEBRACIONES")}</p><h2 id="celebrations-title">{t("Hay días que se esperan.")}<br /><span>{t("Y se recuerdan para siempre.")}</span></h2><p>{t("Antes de la primera foto y del primer abrazo, hay una invitación. Hagamos que la tuya se sienta tan especial como lo que estás por celebrar.")}</p></div>
        <div ref={selectorRef} className={`event-selector event-choice-gallery${revealed ? " is-revealed" : ""}`} role="group" aria-label={english ? "Choose a celebration" : "Elige una celebración"}>
          {celebrations.map((item, index) => <button type="button" className={`event-choice event-choice-${item.theme}`} key={item.theme} aria-expanded={expanded && active === index} aria-controls="event-experience" onClick={() => { setExpanded(current => active === index ? !current : true); setActive(index); setDetail(null); }}><img src={item.image} alt="" loading="lazy" width={1024} height={1536} /><span className="event-choice-icon"><item.Icon size={22} aria-hidden="true" /></span><span className="event-choice-copy"><strong>{labels[index]}</strong><span>{t(item.subtitle)}</span><small>{expanded && active === index ? (english ? "Close experience" : "Cerrar experiencia") : (english ? "Discover the experience" : "Descubre la experiencia")}<ArrowUpRight size={16} aria-hidden="true" /></small></span></button>)}
        </div>
        <div id="event-experience" className={`event-experience${expanded ? " is-expanded" : ""}`} inert={!expanded}><div className="event-experience-clip"><div className="event-experience-content">
        <div id="event-showcase" className={`event-showcase event-theme-${event.theme}`}>
          <div className="event-story" key={`story-${active}`}>
            <span className="event-chapter">0{active + 1} / {english ? "YOUR NEXT MEMORY" : "TU PRÓXIMO RECUERDO"}</span>
            <span className="event-story-icon"><Icon size={25} aria-hidden="true" /></span>
            <h3>{active === 0 ? (english ? "Your entire wedding, in one place." : "Toda su boda, en un solo lugar.") : t(event.subtitle)}</h3><p>{active === 0 ? (english ? "From your story and photos to the last detail of the big day. A wedding website your guests can consult whenever they need, with the information you keep up to date." : "Desde su historia y sus fotos hasta el último detalle del gran día. Una aplicación web que sus invitados pueden consultar cuando quieran, con la información que ustedes mantienen al día.") : t(event.description)}</p>
            <div className="event-possibilities"><span><Check size={15} />{english ? "A design that feels like you" : "Un diseño que se siente como tú"}</span><span><Check size={15} />{english ? "All the details in one place" : "Todos los detalles en un lugar"}</span><span><Check size={15} />{english ? "Made to share from your phone" : "Lista para compartir desde tu celular"}</span></div>
            <a className="event-contact" href={contact} target="_blank" rel="noopener noreferrer">{t("Planeemos algo especial")}<ArrowUpRight size={18} aria-hidden="true" /></a>
            <p className="event-scope">{active === 0 ? (english ? "Guest features and a private dashboard for the couple are defined in your proposal." : "Las funciones para invitados y el panel privado de los novios se definen en su propuesta.") : (english ? "RSVP, maps and schedules can be included according to your project." : "Confirmación de asistencia, mapas y agenda según lo que necesite tu proyecto.")}</p>
          </div>
          <div className="event-stage">
            <span className="event-stage-caption">{english ? "A LITTLE PREVIEW OF THE MAGIC" : "UN VISTAZO A LA MAGIA"}</span>
            <span className="event-orbit event-orbit-one" aria-hidden="true" /><span className="event-orbit event-orbit-two" aria-hidden="true" />
            <Sparkles className="event-spark event-spark-one" size={26} aria-hidden="true" /><Sparkles className="event-spark event-spark-two" size={18} aria-hidden="true" />
            <div className="invitation-phone">
              <div className="invitation-screen" key={active}>
                <div className="invitation-cover"><img src={event.image} alt="" loading="lazy" width={1024} height={1536} /><div className="invitation-cover-copy"><span>{t(event.kicker)}</span><h4>{event.name}</h4><p>{english ? event.englishGreeting : event.greeting}</p></div></div>
                <div className="invitation-body"><span className="invitation-date">{event.date}</span><div className="invitation-flourish" aria-hidden="true"><span /><Icon size={16} /><span /></div><p>{english ? "Save a place in your calendar" : "Guarda un lugar en tu calendario"}</p>
                  <div className="invitation-tools"><button type="button" onClick={() => setDetail("location")}><MapPin size={16} />{english ? "Location" : "Ubicación"}</button><button type="button" onClick={() => setDetail("agenda")}><CalendarDays size={16} />{english ? "Schedule" : "Agenda"}</button></div>
                  <button type="button" className="invitation-rsvp" onClick={() => setDetail("rsvp")}>{t("Confirma tu asistencia")}<Heart size={14} aria-hidden="true" /></button>
                  <span className="invitation-example">{english ? "SAMPLE INVITATION" : "INVITACIÓN DE EJEMPLO"}</span>
                </div>
                {detail && <div className="invitation-detail" role="status"><button type="button" className="invitation-detail-close" aria-label={english ? "Close detail" : "Cerrar detalle"} onClick={() => setDetail(null)}><X size={18} /></button><Icon size={24} /><h5>{detail === "location" ? event.place : detail === "agenda" ? (english ? "Our meeting" : "Nuestra cita") : (english ? "We'll save you a place" : "Te guardamos un lugar")}</h5><p>{detail === "location" ? (english ? "Your invitation can show the address and directions to your celebration." : "Tu invitación puede mostrar la dirección y cómo llegar a tu celebración.") : detail === "agenda" ? `${event.date} · ${event.time}` : (english ? "Your guests can confirm their attendance here. This is a sample; no information is sent." : "Aquí tus invitados pueden confirmar su asistencia. Esta es una muestra; no se envían datos.")}</p><small>{english ? "Interactive sample · fictional details" : "Muestra interactiva · datos ficticios"}</small></div>}
              </div>
            </div>
            <span className="event-stage-footnote">{english ? "Try the invitation's buttons" : "Prueba los botones de la invitación"}</span>
          </div>
        </div>
        {active === 0 && <div className="wedding-hub">
          <div className="wedding-guest-info"><p className="eyebrow">{english ? "FOR YOUR GUESTS" : "PARA SUS INVITADOS"}</p><h3>{english ? "Every detail, always at hand." : "Cada detalle, siempre a la mano."}</h3><p>{english ? "One link to discover your story, plan the day and check the latest details without searching through messages." : "Un solo enlace para conocer su historia, organizarse para el gran día y consultar los detalles actualizados sin buscar entre mensajes."}</p><div className="wedding-memory"><img src="/demo-wedding-v2.jpg" alt="" loading="lazy" width={1024} height={1536} /><div><span>{english ? "OUR STORY" : "NUESTRA HISTORIA"}</span><strong>Valeria & Mateo</strong><small>18 · 09 · 2027</small></div><span className="wedding-memory-seal"><Heart size={17} aria-hidden="true" />{english ? "A day to remember" : "Un día para recordar"}</span></div><div className="wedding-feature-grid">
            <span><Heart size={18} aria-hidden="true" /><strong>{english ? "Your story & photos" : "Su historia y sus fotos"}</strong><small>{english ? "Meet the couple and explore their gallery." : "Conozcan a los novios y recorran su galería."}</small></span>
            <span><Sparkles size={18} aria-hidden="true" /><strong>{english ? "Dress code" : "Código de vestimenta"}</strong><small>{english ? "Style, colors and recommendations." : "Estilo, colores y recomendaciones."}</small></span>
            <span><CalendarDays size={18} aria-hidden="true" /><strong>{english ? "Date & schedule" : "Fecha y horarios"}</strong><small>{english ? "Ceremony, reception and the day's agenda." : "Ceremonia, recepción y agenda del día."}</small></span>
            <span><MapPin size={18} aria-hidden="true" /><strong>{english ? "Locations & more" : "Ubicaciones y más"}</strong><small>{english ? "Directions, gift registry and useful details." : "Cómo llegar, mesa de regalos y detalles útiles."}</small></span>
          </div></div>
          <div className="wedding-couple-info"><p className="eyebrow">{english ? "FOR THE COUPLE" : "PARA LOS NOVIOS"}</p><h3>{english ? "Your guest list, under control." : "Su lista de invitados, bajo control."}</h3><p>{english ? "We can include a private dashboard to consult your guest list, confirmations and pending replies, and organize the celebration with clarity." : "Podemos incluir un dashboard privado para consultar su lista de invitados, ver quién confirmó y quién está pendiente, y organizar la celebración con claridad."}</p>
            <div className="wedding-dashboard" aria-label={english ? "Illustrative guest dashboard" : "Ejemplo ilustrativo del panel de invitados"}><div className="wedding-dashboard-heading"><span><Users size={17} aria-hidden="true" />{english ? "Guest list" : "Lista de invitados"}</span><small>{english ? "SAMPLE" : "EJEMPLO"}</small></div><div className="wedding-dashboard-stats"><span><strong>120</strong>{english ? "Guests" : "Invitados"}</span><span><strong>86</strong>{english ? "Confirmed" : "Confirmados"}</span><span><strong>34</strong>{english ? "Pending" : "Pendientes"}</span></div><div className="wedding-progress"><div className="wedding-progress-ring"><strong>72<small>%</small></strong></div><div><strong>{english ? "The celebration is taking shape" : "La celebración toma forma"}</strong><span>{english ? "86 of 120 guests have confirmed" : "86 de 120 invitados confirmaron"}</span><small>{english ? "Rounded percentage · sample data" : "Porcentaje redondeado · datos de ejemplo"}</small></div></div><div className="wedding-dashboard-row"><span><i>AM</i>Ana Martínez</span><span className="wedding-status-confirmed">{english ? "Confirmed" : "Confirmado"}</span></div><div className="wedding-dashboard-row"><span><i>DL</i>Diego López</span><span>{english ? "Pending" : "Pendiente"}</span></div><div className="wedding-dashboard-row"><span><i>SR</i>Sofía Ruiz</span><span className="wedding-status-confirmed">{english ? "Confirmed" : "Confirmado"}</span></div><p>{english ? "Fictional data · Dashboard design sample" : "Datos ficticios · Muestra de diseño del panel"}</p></div>
          </div>
        </div>}
        {active !== 0 && <div className={`wedding-hub event-hub-${event.theme}`} key={`hub-${active}`}>
          <div className="wedding-guest-info"><p className="eyebrow">{english ? "FOR YOUR ATTENDEES" : active === 1 ? "PARA TUS INVITADOS" : "PARA LOS ASISTENTES"}</p><h3>{experience.guestTitle}</h3><p>{experience.guestCopy}</p>
            <div className="wedding-memory"><img src={event.image} alt="" loading="lazy" width={1024} height={1536} /><div><span>{t(event.kicker)}</span><strong>{event.name}</strong><small>{event.date}</small></div><span className="wedding-memory-seal"><Icon size={17} aria-hidden="true" />{english ? "Your next memory" : active === 1 ? "Celebra a tu manera" : "Ideas que conectan"}</span></div>
            <div className="wedding-feature-grid">{experience.features.map(([title, copy], index) => { const FeatureIcon = [Icon, CalendarDays, MapPin, Sparkles][index]; return <span key={title}><FeatureIcon size={18} aria-hidden="true" /><strong>{title}</strong><small>{copy}</small></span>; })}</div>
          </div>
          <div className="wedding-couple-info"><p className="eyebrow">{experience.owner}</p><h3>{experience.ownerTitle}</h3><p>{experience.ownerCopy}</p>
            <div className="wedding-dashboard" aria-label={english ? "Illustrative organizer dashboard" : "Ejemplo ilustrativo del panel de organización"}><div className="wedding-dashboard-heading"><span><Users size={17} aria-hidden="true" />{experience.list}</span><small>{english ? "SAMPLE" : "EJEMPLO"}</small></div>
              <div className="wedding-dashboard-stats"><span><strong>{experience.total}</strong>{active === 1 ? (english ? "Invited" : "Invitados") : (english ? "Capacity" : "Cupo total")}</span><span><strong>{experience.confirmed}</strong>{active === 1 ? (english ? "Confirmed" : "Confirmados") : (english ? "Registered" : "Registrados")}</span><span><strong>{experience.pending}</strong>{active === 1 ? (english ? "Pending" : "Pendientes") : (english ? "Available" : "Disponibles")}</span></div>
              <div className="wedding-progress"><div className="wedding-progress-ring" style={{ background: `conic-gradient(var(--hub-chart, #8b6cb9) 0% ${experience.percent}%, #ded5ec ${experience.percent}% 100%)` }}><strong>{experience.percent}<small>%</small></strong></div><div><strong>{experience.progress}</strong><span>{active === 1 ? (english ? "42 guests have confirmed" : "42 invitados confirmaron") : (english ? "108 of 150 places reserved" : "108 de 150 lugares reservados")}</span><small>{english ? "Sample data" : "Datos de ejemplo"}</small></div></div>
              {["Ana Martínez", "Diego López", "Sofía Ruiz"].map((name, index) => <div className="wedding-dashboard-row" key={name}><span><i>{name.split(" ").map(part => part[0]).join("")}</i>{name}</span><span className={active === 2 || index !== 1 ? "wedding-status-confirmed" : undefined}>{active === 2 ? (english ? "Registered" : "Registrado") : index === 1 ? (english ? "Pending" : "Pendiente") : (english ? "Confirmed" : "Confirmado")}</span></div>)}
              <p>{english ? "Fictional data · Dashboard design sample" : "Datos ficticios · Muestra de diseño del panel"}</p>
            </div>
          </div>
        </div>}
        </div></div></div>
        <div className="event-plans" aria-labelledby="event-plans-title">
          <div className="event-plans-heading"><p className="eyebrow">{english ? "A PLAN FOR YOUR CELEBRATION" : "UN PLAN PARA TU CELEBRACIÓN"}</p><h3 id="event-plans-title">{english ? "Choose how you want to experience your event." : "Cada celebración tiene su forma de brillar."}</h3><p>{english ? "For weddings, celebrations and simple gatherings. We agree on the details of your event before we begin." : "Cuéntanos qué estás preparando. Encontramos contigo la opción que mejor acompañe tu boda, tu fiesta o tu encuentro."}</p></div>
          <div className="event-plans-grid">{[
            { name: "Bruma", level: english ? "Your digital invitation" : "Tu invitación digital", price: "$1,499", Icon: Heart, subtitle: english ? "Your celebration starts with a beautiful invitation." : "Ese primer vistazo que hace sentir: ya quiero estar ahí.", features: english ? ["Personalized design from our collection", "Up to 30 optimized photos", "Date, location and directions", "Dress code and schedule", "Event subdomain included", "3 revision rounds", "Hosting: up to 12 months before + 30 days after the event", "WhatsApp support from delivery through 30 days after the event"] : ["Diseño de catálogo personalizado", "Hasta 30 fotos optimizadas", "Fecha, ubicación y cómo llegar", "Código de vestimenta y agenda", "Subdominio del evento incluido", "3 rondas de cambios", "Alojamiento: hasta 12 meses antes + 30 días después", "Soporte por WhatsApp desde la entrega hasta 30 días después del evento"] },
            { name: "Aurora", level: english ? "Invitation + guest management" : "Invitación + gestión de invitados", price: "$2,999", Icon: Users, subtitle: english ? "All the details and your guest list in one place." : "Todo a la mano, para ti y para quienes te acompañan.", features: english ? ["Everything in Bruma", "Online attendance confirmation", "Private organizer dashboard", "Up to 300 guests and RSVP tracking", "Confirmed and pending guest overview", "Guest list and RSVP download before closing"] : ["Todo lo de Bruma", "Confirmación de asistencia en línea", "Dashboard privado del organizador", "Hasta 300 invitados y sus respuestas", "Resumen de confirmados y pendientes", "Descarga de lista y confirmaciones antes del cierre"] },
            { name: "Boreal", level: english ? "A more personalized experience" : "Una experiencia más personalizada", price: "$4,999", Icon: Sparkles, subtitle: english ? "An experience with its own personality." : "Para darle a tu día esos detalles que lo hacen muy tuyo.", features: english ? ["Everything in Aurora", "More personalized visual design", "QR passes or seating management, as quoted", "Additional features agreed in your proposal", "Scope tailored to your celebration", "Priority support"] : ["Todo lo de Aurora", "Diseño visual más personalizado", "Pases QR o mesas, según cotización", "Funciones adicionales acordadas", "Alcance adaptado a tu celebración", "Atención prioritaria"] },
          ].map((plan, index) => <article className={`event-plan event-plan-${index}`} key={plan.name}>
            <div className="event-plan-top"><span className="event-plan-emblem"><plan.Icon size={24} aria-hidden="true" /></span>{index === 1 && <span>{english ? "WITH GUEST MANAGEMENT" : "CON GESTIÓN DE INVITADOS"}</span>}</div><h4>{plan.name}</h4><span className="event-plan-level">{plan.level}</span><p className="event-plan-subtitle">{plan.subtitle}</p><p className="event-plan-price">{index === 2 && <small>{english ? "From" : "Desde"} </small>}{plan.price}<span> MXN</span></p><ul>{plan.features.map(feature => <li key={feature}><Check size={15} aria-hidden="true" />{feature}</li>)}</ul><a href={`https://wa.me/528111197607?text=${encodeURIComponent(english ? `Hi! I am interested in ${plan.name} for my event. The reference price is ${index === 2 ? "from " : ""}${plan.price} MXN. I would like to agree on the scope and get a quote.` : `¡Hola! Me interesa ${plan.name} para mi evento. El precio de referencia es ${index === 2 ? "desde " : ""}${plan.price} MXN. Quisiera definir el alcance y recibir una cotización.`)}`} target="_blank" rel="noopener noreferrer">{english ? "Discuss this plan" : "Platiquemos de tu evento"}<ArrowUpRight size={17} aria-hidden="true" /></a>
          </article>)}</div>
          <div className="event-care">
            <div className="event-care-heading"><Sparkles size={22} aria-hidden="true" /><div><span>{english ? "THE DETAILS ARE TAKEN CARE OF" : "TE ACOMPAÑAMOS EN LOS DETALLES"}</span><h4>{english ? "You celebrate. We take care of your web experience." : "Que preparar tu evento también se disfrute."}</h4></div></div>
            <div className="event-care-highlights"><span><Heart size={18} aria-hidden="true" /><strong>{english ? "30 optimized photos" : "30 fotos optimizadas"}</strong><small>{english ? "Your memories, ready to share" : "Un espacio para las fotos que cuentan tu historia"}</small></span><span><Check size={18} aria-hidden="true" /><strong>{english ? "3 revision rounds" : "3 rondas de cambios"}</strong><small>{english ? "To make the design feel like you" : "Lo revisamos contigo, hasta cuidar los detalles"}</small></span><span><CalendarDays size={18} aria-hidden="true" /><strong>{english ? "12 months before + 30 days after" : "12 meses antes + 30 días después"}</strong><small>{english ? "Up to 12 months before your event" : "Desde la ilusión de planear hasta después del gran día"}</small></span></div>
            <div className="event-care-details">{[
              { title: english ? "Your space, your guests" : "Un lugar para tu historia y tu gente", text: english ? "Every plan includes an event subdomain and up to 30 optimized photos. Dashboard plans include up to 300 guests and a guest list and RSVP download before closing. Hosting includes up to 12 months before the event and 30 days after it; additional time and extensions are quoted separately." : "Tu evento tendrá su propio enlace en Nordra y espacio para hasta 30 fotos optimizadas. Si eliges un paquete con dashboard, podrás organizar hasta 300 invitados y descargar tu lista y sus confirmaciones antes del cierre. La página puede acompañarte hasta 12 meses antes del evento y 30 días después. ¿Quieres conservarla más tiempo? Podemos cotizar una extensión." },
              { title: english ? "We accompany you" : "Te acompañamos", text: english ? "WhatsApp support from delivery through 30 days after the event, Monday–Friday, 9:00–18:00 Mexico City time. Initial response within one business day. Includes help using contracted features and fixing malfunctions. Design and content adjustments use the 3 included revision rounds; new features are quoted separately. Boreal includes priority support. Live event-day assistance is an optional add-on with an agreed schedule." : "Si tienes una duda, escríbenos por WhatsApp. Te acompañamos desde la entrega hasta 30 días después del evento, de lunes a viernes de 9:00 a 18:00, hora de Ciudad de México, con una primera respuesta en máximo un día hábil. Te ayudamos a usar las funciones de tu paquete y corregimos fallas de funcionamiento. Revisamos el diseño y el contenido contigo en 3 rondas de cambios; las funciones nuevas se cotizan aparte. Boreal incluye atención prioritaria. Si necesitas que estemos disponibles en vivo el día del evento, podemos acordar un horario y cotizar ese acompañamiento." },
              { title: english ? "Want your own domain?" : "¿Quieres tu propio dominio?", text: english ? "Optional and subject to availability. We quote one year of registration plus configuration and confirm the price before purchase. The domain belongs to the client, with administration assistance from Nordra. Domain renewal is independent of website hosting." : "Todos los paquetes ya incluyen un enlace de Nordra. Si prefieres una dirección propia, buscamos contigo una disponible y te compartimos el costo del registro por un año y su configuración antes de comprarla. El dominio queda a tu nombre y te ayudamos a administrarlo. Renovar esa dirección y mantener publicada tu página son servicios con vigencias independientes." },
              { title: english ? "Extra features, clear costs" : "Si tu idea necesita algo más", text: english ? "Contracted features are covered by the plan price, including photos, map links and dashboard or RSVPs where included. Sharing your link manually on WhatsApp has no additional charge from Nordra. Paid services such as automated WhatsApp or SMS messages, ticket sales or special integrations require explaining configuration costs and provider fees, and your approval before contracting or activation." : "Lo que acordamos en tu paquete está incluido: tus fotos, enlaces a mapas y, cuando corresponda, el dashboard y las confirmaciones. Puedes compartir tu enlace manualmente por WhatsApp sin un cargo adicional de Nordra. Si quieres sumar mensajes automáticos, venta de entradas o alguna integración de pago, primero te explicamos los costos de configuración y las comisiones del proveedor. Tú decides si seguimos adelante antes de contratar o activar algo." },
              { title: english ? "A gathering with more possibilities" : "¿Estás imaginando un encuentro más grande?", text: english ? "The plans also cover simple gatherings with information, schedule, location and, in dashboard plans, registration for up to 300 attendees. Basic QR passes and guest management can be included in Boreal as quoted. Ticket sales, workshops with independent capacity, customized accreditation or live event operations need a tailored proposal." : "También podemos acompañar tu encuentro con su información, programa y ubicación. Los paquetes con dashboard incluyen registro sencillo de hasta 300 asistentes; en Boreal podemos contemplar pases QR y gestión básica según la cotización. Si estás preparando venta de entradas, talleres con cupos propios, acreditaciones personalizadas o apoyo en vivo, cuéntanos tu idea y armamos una propuesta para lo que necesitas." },
            ].map((item, index) => { const DetailIcon = [Heart, MessageCircle, Globe, SlidersHorizontal, Users][index]; const teasers = english ? ["Your link, photos and guests", "Help before and after your event", "A web address that feels like you", "Choose what you want to add", "A proposal for your gathering"] : ["Tu enlace, tus fotos y tu gente", "Ayuda antes y después de tu evento", "Una dirección que se sienta tuya", "Tú decides qué quieres sumar", "Una propuesta para tu encuentro"]; return <details key={item.title} name="event-service-details"><summary><span className="event-detail-icon"><DetailIcon size={20} aria-hidden="true" /></span><span className="event-detail-label"><strong>{item.title}</strong><small>{teasers[index]}</small></span><span className="event-care-toggle" aria-hidden="true"><ChevronDown className="event-care-chevron" size={18} strokeWidth={1.6} /></span></summary><div className="event-care-body">{item.text.split(/(?<=\.)\s+(?=La página|¿Quieres|Te ayudamos|Revisamos|Premium|Si necesitas|El dominio|Renovar|Puedes|Si quieres|Tú decides|Los paquetes|Si estás)/).map(paragraph => <div className="event-care-point" key={paragraph}><span className="event-care-point-light" aria-hidden="true" /><p>{paragraph.split(/(30 fotos optimizadas|300 invitados|12 meses|30 días|3 rondas de cambios|un día hábil|9:00 a 18:00|a tu nombre|atención prioritaria|sin un cargo adicional de Nordra)/g).map((part, partIndex) => partIndex % 2 ? <strong key={partIndex}>{part}</strong> : part)}</p></div>)}</div></details>; })}</div>
          </div>
        </div>
        <div className="celebrations-note"><p><strong>{t("Tu historia marca el diseño.")}</strong>{" "}{t("Platiquemos sobre el estilo, los detalles y las funciones que necesitas; con eso preparamos una propuesta para tu celebración.")}</p><span>{t("Fotografías de ejemplo · Cada proyecto se personaliza")}</span></div>
      </div>
    </section>
  );
}
